'use client';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';
import ReduxProvider from './redux/provider';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
// import { checkDatabaseConnection } from './redux/slices/databaseSlice';
// import { connectToDB } from '../../lib/db';
// import { store } from './redux/store';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
// connectToDB(store);

function ThemeInitializer() {
  const darkMode = useSelector((state) => state.theme.darkMode);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  return null;
}

export default function RootLayout({ children }) {
  // const dispatch = useDispatch();

  // useEffect(() => {
  //   dispatch(checkDatabaseConnection());
  // }, [dispatch]);

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black transition-colors duration-200`}
        // style={{ fontFamily: "'zombriya', Arial, sans-serif" }}
      >
        <ReduxProvider>
          <ThemeInitializer />
          <ChakraProvider>{children}</ChakraProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
